# Generated by Django 5.1.2 on 2024-10-08 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arrendado',
        ),
    ]
