# Generated by Django 5.1.2 on 2024-10-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmuebles', '0002_delete_arrendado'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedades',
            name='rolDueño',
            field=models.BooleanField(default=False),
        ),
    ]
