# Generated by Django 5.1.2 on 2024-10-08 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmuebles', '0003_propiedades_roldueño'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedades',
            name='rolDueño',
        ),
        migrations.AddField(
            model_name='propiedades',
            name='dueño',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dueño_propiedades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propiedades',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dueñoInquilino', to=settings.AUTH_USER_MODEL),
        ),
    ]
