# Generated by Django 5.1.2 on 2024-10-08 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmuebles', '0004_remove_propiedades_roldueño_propiedades_dueño_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedades',
            name='dueño',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dueño_propiedades', to=settings.AUTH_USER_MODEL),
        ),
    ]
